CC = clang++
GAME_SOURCE = BloodSword.cpp
GAME_OUTPUT = BloodSword.exe
LINKER_FLAGS = -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -stdlib=libc++ -O3 -std=c++17
INCLUDES = -I/usr/include/SDL2 -I/usr/local/include/SDL2

all: clean blood-sword

blood-sword:
	$(CC) -Wall $(GAME_SOURCE) $(LINKER_FLAGS) $(INCLUDES) -o $(GAME_OUTPUT)

clean:
	rm -f *.exe *.o
